apiVersion: v1
kind: Service
metadata:
  namespace: aquaris
  name: {{ include "wordpress.name" .}}
spec:
  type: LoadBalancer
  selector:
    app: {{.Values.app.specs.label}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80